export const data1 = {
  nickname: "test1",
  email: "test1@gmail.com",
  phone: "01012345678",
  address: "서울 중구 세종대로 지하 2 (남대문로5가, 서울역 1호선)",
  profile: "",

  pet: '2',

  petImgSrc: "/imgs/dog3.jpeg",
  name: '버디',
  breed: '골든리트리버',
  sex: 'M',
  birthYear: 2018,
  weight: 25,
  isNeutering: true,
  allergy: false,
  isDisease: false,
  etc: 'Friendly dog',
}
export const data2 = {
  nickname: "test1",
  email: "test1@gmail.com",
  phone: "01012345678",
  address: "서울 중구 세종대로 지하 2 (남대문로5가, 서울역 1호선)",
  profile: "",

  pet: '',
  petImgSrc: "/imgs/dog3.jpeg",
  name: '똑바로',
  breed: '푸들',
  sex: 'W',
  birthYear: 2012,
  weight: 5,
  isNeutering: true,
  allergy: false,
  isDisease: false,
  etc: 'Friendly dog',
}

const Data = [
  { id: 1,
    email: 'john@example.com',
    phone: '123-456-7890',
    address: '123 Main St',
    nickname : 'gildong',
    zipcode : 'abcd',
    roadAddr: 'abcd',
    detailAddr: 'abcd',
    latitude: '123456',
    longitude: '123456',
    profile: '프로필 이미지 url',

    careType: '데이케어',
    serviceArea1: '서울',

    title: '펫시터 경력 30년차',
    contents: '지원합니다',
    photo1: 'url',
    photo2: 'url',
    photo3: 'url',
    photo4: 'url',
    photo5: 'url',
    storedFileName: '사진첨부 파일',
    photoNo: '5개 중에 몇번째 사진인지 숫자로',
    board_id: '1',
    petsitterId: '펫시터 id',

    startDate: '',
    startTime: '',
    endDate: '',
    endTime: '',
    standardPrice: '',
    addPrice: '',
    nightPrice: '',
    fee: '',
    totalPrice: '',
    reservedPets: '예약할 반려견의 인덱스 목록 [6, 7, 8]',

    rating: '',
    review_contents: '',

    pet_storedFileName: '반려견 프로필 경로',

    name: 'Buddy',
    breed: 'Golden Retriever',
    sex: 'M',
    birthYear: 2018,
    weight: 25,
    isNeutering: true,
    allergy: false,
    isDisease: false,
    etc: 'Friendly dog',
    reservations_status: 'approved'
  },
  { id: 2,
    email: 'john@example.com',
    phone: '123-456-7890',
    address: '123 Main St',
    nickname : 'gildong',
    zipcode : 'abcd',
    roadAddr: 'abcd',
    detailAddr: 'abcd',
    latitude: '123456',
    longitude: '123456',
    profile: '프로필 이미지 url',

    careType: '데이케어',
    serviceArea1: '서울',

    title: '펫시터 경력 30년차',
    contents: '지원합니다',
    photo1: 'url',
    photo2: 'url',
    photo3: 'url',
    photo4: 'url',
    photo5: 'url',
    storedFileName: '사진첨부 파일',
    photoNo: '5개 중에 몇번째 사진인지 숫자로',
    board_id: '1',
    petsitterId: '펫시터 id',

    startDate: '',
    startTime: '',
    endDate: '',
    endTime: '',
    standardPrice: '',
    addPrice: '',
    nightPrice: '',
    fee: '',
    totalPrice: '',
    reservedPets: '예약할 반려견의 인덱스 목록 [6, 7, 8]',

    rating: '',
    review_contents: '',

    pet_storedFileName: '반려견 프로필 경로',

    name: 'Buddy',
    breed: 'Golden Retriever',
    sex: 'M',
    birthYear: 2018,
    weight: 25,
    isNeutering: true,
    allergy: false,
    isDisease: false,
    etc: 'Friendly dog',
    reservations_status: 'approved'
  },
  { id: 3,
    email: 'john@example.com',
    phone: '123-456-7890',
    address: '123 Main St',
    nickname : 'gildong',
    zipcode : 'abcd',
    roadAddr: 'abcd',
    detailAddr: 'abcd',
    latitude: '123456',
    longitude: '123456',
    profile: '프로필 이미지 url',

    careType: '데이케어',
    serviceArea1: '서울',

    title: '펫시터 경력 30년차',
    contents: '지원합니다',
    photo1: 'url',
    photo2: 'url',
    photo3: 'url',
    photo4: 'url',
    photo5: 'url',
    storedFileName: '사진첨부 파일',
    photoNo: '5개 중에 몇번째 사진인지 숫자로',
    board_id: '1',
    petsitterId: '펫시터 id',

    startDate: '',
    startTime: '',
    endDate: '',
    endTime: '',
    standardPrice: '',
    addPrice: '',
    nightPrice: '',
    fee: '',
    totalPrice: '',
    reservedPets: '예약할 반려견의 인덱스 목록 [6, 7, 8]',

    rating: '',
    review_contents: '',

    pet_storedFileName: '반려견 프로필 경로',

    name: 'Buddy',
    breed: 'Golden Retriever',
    sex: 'M',
    birthYear: 2018,
    weight: 25,
    isNeutering: true,
    allergy: false,
    isDisease: false,
    etc: 'Friendly dog',
    reservations_status: 'approved'
  },
  { id: 4,
    email: 'john@example.com',
    phone: '123-456-7890',
    address: '123 Main St',
    nickname : 'gildong',
    zipcode : 'abcd',
    roadAddr: 'abcd',
    detailAddr: 'abcd',
    latitude: '123456',
    longitude: '123456',
    profile: '프로필 이미지 url',

    careType: '데이케어',
    serviceArea1: '서울',

    title: '펫시터 경력 30년차',
    contents: '지원합니다',
    photo1: 'url',
    photo2: 'url',
    photo3: 'url',
    photo4: 'url',
    photo5: 'url',
    storedFileName: '사진첨부 파일',
    photoNo: '5개 중에 몇번째 사진인지 숫자로',
    board_id: '1',
    petsitterId: '펫시터 id',

    startDate: '',
    startTime: '',
    endDate: '',
    endTime: '',
    standardPrice: '',
    addPrice: '',
    nightPrice: '',
    fee: '',
    totalPrice: '',
    reservedPets: '예약할 반려견의 인덱스 목록 [6, 7, 8]',

    rating: '',
    review_contents: '',

    pet_storedFileName: '반려견 프로필 경로',

    name: 'Buddy',
    breed: 'Golden Retriever',
    sex: 'M',
    birthYear: 2018,
    weight: 25,
    isNeutering: true,
    allergy: false,
    isDisease: false,
    etc: 'Friendly dog',
    reservations_status: 'approved'
  },
];

